export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#0A0A0B] text-[#E4E4E7] p-8 max-w-3xl mx-auto">
      <h1 className="text-3xl font-bold mb-6">Terms and Conditions</h1>
      <p className="text-sm text-[#9494AD] mb-8">Last updated: April 3, 2026</p>

      <div className="space-y-6 text-sm leading-relaxed text-[#9494AD]">
        <section>
          <h2 className="text-lg font-semibold text-white mb-2">Service Description</h2>
          <p>Operator Dashboard is an AI-powered command center for solo founders. The service generates daily priority tasks, content drafts, market intelligence, and growth suggestions using AI. Optional SMS and Telegram notifications deliver daily briefings and allow task management via text.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white mb-2">Messaging Program</h2>
          <ul className="list-disc pl-6 space-y-1">
            <li><strong>Program Name:</strong> Operator Dashboard Notifications</li>
            <li><strong>Message Frequency:</strong> Up to 4 messages per day (morning briefing, midday check-in, afternoon nudge, evening recap)</li>
            <li><strong>Message Content:</strong> Task reminders, goal updates, growth tips, and AI-generated business advice</li>
            <li><strong>Data Rates:</strong> Standard message and data rates may apply</li>
            <li><strong>Opt-Out:</strong> Reply STOP at any time to stop receiving messages, or remove your phone number from the Settings page</li>
            <li><strong>Help:</strong> Reply HELP for support information</li>
            <li><strong>Support:</strong> Contact support through the dashboard Settings page</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white mb-2">Account</h2>
          <p>You are responsible for maintaining the security of your account credentials. You can delete your account and all associated data at any time from the Settings page.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white mb-2">AI-Generated Content</h2>
          <p>Tasks, content drafts, suggestions, and briefings are generated by AI and should be reviewed before acting on them. The service provides recommendations, not guarantees. You are responsible for any actions you take based on AI-generated content.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white mb-2">Availability</h2>
          <p>We aim to keep the service available 24/7 but do not guarantee uptime. The service may be temporarily unavailable for maintenance or updates.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white mb-2">Plans and Pricing</h2>
          <ul className="list-disc pl-6 space-y-1">
            <li><strong>Local (Free):</strong> Self-hosted, unlimited usage, you manage your own server</li>
            <li><strong>Starter ($9/mo):</strong> Cloud-hosted, managed by us</li>
            <li><strong>Pro ($29/mo):</strong> Dedicated VPS, priority support</li>
          </ul>
          <p className="mt-2">Paid plans can be cancelled at any time through the Stripe customer portal. Refunds are handled on a case-by-case basis.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white mb-2">Changes</h2>
          <p>We may update these terms from time to time. Continued use of the service after changes constitutes acceptance of the updated terms.</p>
        </section>
      </div>
    </div>
  );
}
